### PR TITLE
2016-17 Update

### PR DESCRIPTION
**Pull request by tdav16**
Updating the repository files to their latest versions.

### CODE REVIEW

**Comment by javajawa** [comment]
The change of ```<!--SRVROOT-->``` to ```/scc/icsf``` breaks my test environment :(

**Comment by javajawa** [comment]
Also, the ```@icsf.org.uk``` email addresses *should* still work -- although, they are not under my maintenance. The domain is still pointing to us at the very least. Is the file/document called "wert" still around? Details will be in there.

**Comment by tdav16** [comment]
I haven't found a file called 'wert'. Any pointers as to where it should be?

**Comment by javajawa** [comment]
It was originally in an email, which might still be in the Tech Priest gmail -- otherwise, I last heard of it with @Darael was running things.

**Comment by tdav16** [comment]
I haven't found anything in the gmail account so far.

**Comment by Darael** [comment]
I can't say I recall a file called "wert".

A problem I ran into with password resets during my tenure as Tech Priest was that Google wanted to know when the accounts were created, and that information is not in the handover document I was given.  Dost have a note of it anywhere, @javajawa?  It should probably go in to the next iteration anyway.

**Comment by javajawa** [comment]
The accounts were created sometime between my ascension to tech priest in 2009-09 and 2010-10-18 (which is when the email called 'wert' was originally sent!).

Also, re-reading these notes, there's not a lot of still-useful information; the passwords should have changed, and the redirects will hopefully be in Darael's doc.
I have contacted the admin who controls icsf.(org|co).uk.

**Comment by tdav16** [comment]
I have the crash guide - at least some of the passwords have changed. Our email situation is slightly ad-hoc right now.

**Comment by rjw1** [comment]
So the current list of aliases is as follows.

```
bobwalker@AMACHINE:~/git/ashbrook-hosting/icsf.org.uk/config ☃ >cat aliases
icsf: icsf@imperial.ac.uk
librarian: icsf.librarian@gmail.com
webeditor: icsf.webeditor@gmail.com
archivist: icsf.archivist@gmail.com
chair: icsf.chairentity@gmail.com
vicechair: icsf.chairofvice@gmail.com
secretary: icsf.secretary@gmail.com
treasurer: icsf.treasurer@gmail.com
editor: icsf.editor@gmail.com
picocon: icsf.picoconsofa@gmail.com
publicity: icsf.publicity@gmail.com
techpriest: icsf.techpriest@gmail.com
teampunk: icsf.steampunk@gmail.com
steampunk: icsf.steampunk@gmail.com
```

to be honest at this point i suspect that some mails routed through my machine and those aliases may not get through.
I'm happy to change things if need be. 

I've also just renewed the domains.

**Comment by jdranczewski** [comment]
Closed, as this is old now, and any changes have been incorporated into #8 instead. Please let me know if I missed something, I was going off of the version of the website that was live at https://www.union.ic.ac.uk/scc/icsf/ in the summer of 2021

**Pull request closed without merging**
